[package]
name = "xenith-vm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
xenith-diag = { workspace = true }
xenith-syntax = { workspace = true }
xenith-sema = { workspace = true }
